%YAML:1.0
---
extrinsics: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, 0.0,  # 第一行：旋转和平移
          0.0, 1.0, 0.0, 0.0,  # 第二行：旋转和平移
          0.0, 0.0, 1.0, 0.0,  # 第三行：旋转和平移
          0.0, 0.0, 0.0, 1.0]  # 第四行：齐次坐标
